### ISSUE TITLE
NOA Harvester Error

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#107]
### Please describe the expected behaviour
The NOA harvester should continue collecting datasets from where it left off.

### Please describe the actual behaviour
When we are running the NOA harvester, the harvester finishes successfully without collecting any data. But the logs show something different:

````
ckan_1        | https://sentinels.space.noa.gr/dhus/search?q=ingestiondate:[2019-05-05T19:18:04.717Z TO NOW] AND NOT producttype:RAW&orderby=ingestiondate asc&start=0&rows=100
ckan_1        | Traceback (most recent call last):
ckan_1        |   File "/usr/bin/paster", line 11, in <module>
ckan_1        |     sys.exit(run())
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan_1        |     invoke(command, command_name, options, args[1:])
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan_1        |     exit_code = runner.run(args)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ckan_1        |     result = self.command()
ckan_1        |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 185, in command
ckan_1        |     gather_callback(consumer, method, header, body)
ckan_1        |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/queue.py", line 298, in gather_callback
ckan_1        |     harvest_object_ids = gather_stage(harvester, job)
ckan_1        |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/queue.py", line 352, in gather_stage
ckan_1        |     harvest_object_ids = harvester.gather_stage(job)
ckan_1        |   File "/usr/lib/python2.7/site-packages/ckanext/nextgeossharvest/harvesters/esa.py", line 175, in gather_stage
ckan_1        |     password)
ckan_1        |   File "/usr/lib/python2.7/site-packages/ckanext/nextgeossharvest/lib/opensearch_base.py", line 81, in _crawl_results
ckan_1        |     verify=False, timeout=timeout)
ckan_1        |   File "/usr/lib/python2.7/site-packages/requests/api.py", line 70, in get
ckan_1        |     return request('get', url, params=params, **kwargs)
ckan_1        |   File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
ckan_1        |     return session.request(method=method, url=url, **kwargs)
ckan_1        |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
ckan_1        |     resp = self.send(prep, **send_kwargs)
ckan_1        |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
ckan_1        |     r = adapter.send(request, **kwargs)
ckan_1        |   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
ckan_1        |     raise ConnectionError(e, request=request)
ckan_1        | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sentinels.space.noa.gr', port=443): Max retries exceeded with url: /dhus/search?q=ingestiondate:[2019-05-05T19:18:04.717Z%20TO%20NOW]%20AND%20NOT%20producttype:RAW&orderby=ingestiondate%20asc&start=0&rows=100 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe9ed0f7ad0>: Failed to establish a new connection: [Errno -3] Try again',))
ckan_1        | INFO:repoze.who:request classification: browser
ckan_1        | INFO:repoze.who:-- repoze.who request started (/dataset/c25eadb7-dee5-452a-bd08-a3aefb9cbea0) --
ckan_1        | INFO:repoze.who:no identities found, not authenticating
````

If we check the [_crawl_results](https://github.com/NextGeoss/ckanext-nextgeossharvest/blob/master/ckanext/nextgeossharvest/lib/opensearch_base.py#L63) in opensearch_base.py maybe something worth checking there too.

### What steps can be taken to reproduce the issue?
I've encountered this issue on production. Can't reproduce locally

**Comment by davidcordeiro-deimos** [comment]
Good afternoon,

I have been looking into this issue, and as a first analysis, the following line:

> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sentinels.space.noa.gr', port=443): Max retries exceeded with url: /dhus/search?q=ingestiondate:[2019-05-05T19:18:04.717Z%20TO%20NOW]%20AND%20NOT%20producttype:RAW&orderby=ingestiondate%20asc&start=0&rows=100 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe9ed0f7ad0>: Failed to establish a new connection: [Errno -3] Try again',))

Indicates that the problem is due to either lack of Internet connection in the production environment, or due to being blocked by the NOA server due to many connection retries in a short period of time (DDOS prevention measures). And thus, probably why you are not able to reproduce the same error in a local environment.

Also, if the job is being finished and not aborted (even though without any products collected) also indicates that the exception is probably being caught, and exiting in a clean manner. 

Due to the two previous points, I believe that this issue is happening in [_craw_results](https://github.com/NextGeoss/ckanext-nextgeossharvest/blob/master/ckanext/nextgeossharvest/lib/opensearch_base.py#L63), and we are receiving a status code != 200, and if so, this error should be logged in [provider_logger](https://github.com/NextGeoss/ckanext-nextgeossharvest/blob/master/ckanext/nextgeossharvest/lib/nextgeoss_base.py#L306) / dataproviders_info.log.

@JGulic I would appreciate if you could provide these logs, so we can further pinpoint the cause of the error.

Regards,
David

**Comment by michellecbox** [comment]
following

**Comment by JGulic** [comment]
Not reproducible.
