### ISSUE TITLE
MODIS harvester error

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#114]
### Please describe the expected behaviour
The MODIS harvester should collect all the datasets without an error.

### Please describe the actual behaviour
The MODIS harvester using the following confiuration
````
{
"collection": "MYD13Q1",
"start_date": "2018-01-01T00:00:00Z",
"make_private": false
}
````
runs and collects 290 datasets successfully per run, but also shows that 4 datasets have an error.
The error is the following:
````
 Creation error for g1501225849-lpdaac_ecs: Solr returned an  error: (u"Solr responded with an error (HTTP 400): [Reason: Couldn't  parse shape 'POLYGON ((121.2824719 77.85179909999999, 179.7441524  83.1074874, -8.018294300000001 85.2173779, 60.5906497 78.92895179999999,  121.2824719 77.85179909999999))' because:  com.vividsolutions.jts.geom.TopologyException: side location conflict [  (121.2824719, 77.8517991, NaN) ]]",)

````

### What steps can be taken to reproduce the issue?
Create a new MODIS harvester or use the one that you already have.
Run it few times and check the error.
For us it took few runs for the harvester to start to trow these errors.

**Comment by davidcordeiro-deimos** [comment]
Regarding this issue, I would like to know if there is any limitation in the number of decimal places within Solr.

I am just asking this because I am not able to reproduce this error. As you can see in the logs and ckan page the product g1501225849-lpdaac_ecs (the one presented originally in the issue) has been harvested successfully. 

![log_g1501225849-lpdaac_ecs](https://user-images.githubusercontent.com/46027889/68212345-3f7e4b80-ffd1-11e9-8b86-d9fba7a6b0d9.png)

![ckan_g1501225849-lpdaac_ecs](https://user-images.githubusercontent.com/46027889/68212351-4442ff80-ffd1-11e9-9bb4-6ec0535b7eaf.png)

**Comment by georgiana-b** [comment]
Couldn't reproduce the error locally. I was able to import the dataset in question locally using the latest version on `master` of `ckanext-nextgeossharvest`:

![image](https://user-images.githubusercontent.com/8862002/69800551-c213b880-11d5-11ea-90a6-23d1c300a948.png)

**Comment by JGulic** [comment]
I also can't reproduce this issue locally.
I am closing the issue and we will open a new one if we face the same issue again.
