### ISSUE TITLE
ProbaV harvester improvements

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#134]
Since we are making changes to the harvesters this will be a good opportunity to make changes to the ProbaV harvester.

The ProbaV harvester doesn't follow the structure of the other harvesters. It would be nice if we can spend time to fix this.

**Comment by joaandrade** [comment]
@JGulic the Proba-V harvester has a different structure since we are handling different types of datasets. For some collections, there is a single dataset per day on the original source but, on our side, we are considering each tile as a separated dataset. The logic for this harvester is more complex than the others due to the differences on the original data. At this point, we should spend time fixing the blocking issues that do not allow the harvesters to run (mainly the metadata fields causing indexing problems).

**Comment by georgiana-b** [comment]
@JGulic After taking a thorough look at this harvester I've come to understand why it diverges so much from the structure of other harvesters. There is a significant difference between how the resources of different collections need to be fetched and parsed. Hence the whole code follows these parallel tracks depending on the collection.

What worries me more is that there is no logic to update the datasets/resources. Since we're aiming for that in other harvesters maybe we should open a new PR or rename this one to provide `update_all` for ProbaV too.

**Comment by joaandrade** [comment]
The logic to update the datasets/resources was added in the PR #190 
I suggest to close this issue.
