### ISSUE TITLE
Sentinel harvester: update_all doesn't update the dataset metadata

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#146]
The problem for this issue when running `update_all: True` is here: https://github.com/NextGeoss/ckanext-nextgeossharvest/blob/master/ckanext/nextgeossharvest/lib/nextgeoss_base.py#L290

The extras are preserved, and that is the reason why the dataset still has the original metadata.
Make sure we are updating the data with the updated one

**Comment by davidcordeiro-deimos** [comment]
@JGulic What should be the expected behavior of this function?

- Replace the fields in common with the most recent version of the dataset. Regarding the fields that do not intersect, keep the fields from old dataset and add the fields of the recent dataset.
- Replace the fields in common with the most recent version of the dataset. Regarding the fields that do not intersect, ignore / delete the fields from old dataset and add the fields of the recent dataset. (i.e. the result is only the most recent version of the dataset)

**Comment by davidcordeiro-deimos** [comment]
@JGulic Any feedback on this topic?

**Comment by JGulic** [comment]
@davidcordeiro-deimos so we need to remove the metadata that we are removing from the dataset from the database too, and this function keeps the data.
If for example you removed size from the dataset metadata, when this function gets called, the size metadata field won't be present in the package metadata. But then we get to this function, and this function checks the metadata that we have for the particular pacakge. It sees that size is not part of the new metadata, so it decides to keep size as part of the metadata, although size is not present in the new one.

The function has been implemented in that way, so we are sure that we won't loose some important data that we should have there.

So you need to change the function, to check, if the filed is not part of the new metadata and it belongs to the list of fields that we want to remove and remove the filed from the dataset metadata.
Let me know if this helps.

**Comment by davidcordeiro-deimos** [comment]
@JGulic After discussing this with @joaandrade, our conclusions are as follows:

- For the datasets that only have 1 data provider, the approach should be to replace entirely the old extras dictionary with the new dictionary collected. Which will be already "cleaned" of the unnecessary fields. Thus, not requiring explicit removal of the fields (done during the content parsing).

- For the datasets that have 2 or more data providers (in our current situation, we only have sentinel products), the approach will have to be slightly different. In this case, we will expand the new dictionary with fields from the old dictionary, if the key does not belong to the list (#124 and #126 ). So opposed to the first scenario, the removal is explicit, which is necessary due to the fact that different data providers might have different fields.

As we see it, this way we do not loose any information, without requiring explicit removal of the fields. Please let us know if you agree.

**Comment by davidcordeiro-deimos** [comment]
@JGulic @georgiana-b If we fall back into the discussion that we had in PR #104, clearly my developing / testing environment is not the same as the one used by you. 

However, for this task, this incompability will lead to a similar discussion as the one had in #104, since I am not able to reproduce similar results.

Could you provide me the docker repository, so we are using a similar environment? Note: I tried the one [here](https://github.com/NextGeoss/nextgeoss-ckan-compose), however, it seems that the 2nd and following jobs of a harvester do not receive the information from the previous job.

**Comment by JGulic** [comment]
@davidcordeiro-deimos yes, try to keep the data that belongs to the other provider, and just remove the fields from the list.

Regarding issue #104 I will take a look at the discussion and get back to you

**Comment by davidcordeiro-deimos** [comment]
@JGulic Any feedback on this issue?

**Comment by georgiana-b** [comment]
@davidcordeiro-deimos Looks like we have consensus on how to handle the extras: we add metadata from all the sources and then remove the fields that are part of [the blacklist](https://github.com/NextGeoss/ckanext-nextgeossharvest/issues/124). 

So the bug is that currently those fields from the blacklist are not being removed and that's what we need to address. What is blocking you?

**Comment by georgiana-b** [comment]
As for the testing environment, this is the one we use: 
https://github.com/NextGeoss/nextgeoss-ckan-compose

No sure what you mean by "it seems that the 2nd and following jobs of a harvester do not receive the information from the previous job."
Could you expand on that?

But to be fair, for this task, and other matters of business logic, I don't see why the environment would have that much impact. In  https://github.com/NextGeoss/ckanext-nextgeossharvest/pull/104 the problem also had to do with the code not with the environment.

**Comment by davidcordeiro-deimos** [comment]
@georgiana-b 

Regarding the issue with https://github.com/NextGeoss/nextgeoss-ckan-compose it was a problem with docker setup and cache.

However, it was clear during  #104 that there was a problem with environment, because although we had the same code for this repository, we were obtaining different results. It could be a version problem of the core CKAN or harvest extension.

But if the environment is https://github.com/NextGeoss/nextgeoss-ckan-compose, I will use that as baseline, and proceed with solving this issue.

**Comment by joaandrade** [comment]
The solution for this issue is on PR #198
