### ISSUE TITLE
Plan4All harvester: Ignoring configuration on the first run

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#147]
The PR for Plan4all has been merged to master. But when I was testing it I've encountered the following issue:

The Plan4All harvester ignores the datasets_per_job setting on the first run.

For the testing the datasets_per_job has been set to a 100.
On the first run the harvester collected 197 datasets
Then on the next runs it continued to harvest 100 datasets

Used configuration:
```
{
"datasets_per_job": 100,
"timeout": 60,
"make_private": false
}
```
We can choose if we want to fix this or not. If the number is around 200  datasets for the first run then this is not a problem and we can ignore it.

**Comment by davidcordeiro-deimos** [comment]
@JGulic This is expected behavior from the harvester. In the catalog being harvested, there are products that are not supposed to be harvested, however, it is not possible to filter it out in the query.

Thus the approach was to query the page for a number of products equal to `datasets_per_job`, then during the initial parsing filter out those products, and the remaining to a list to be harvested. 

Now, take into consideration that the query for 1 product takes a similar time to query 100 products (around 40 seconds). Thus, the approach was to fill a list with at least `datasets_per_job` products. After filling the list, the remainder of datasets that had been queried would also be added to the list (in order to avoid slow query times to re-query the same dataset).

So my suggestion to close this issue is to replace the configuration variable name to something more fitting.
