### ISSUE TITLE
EBAS harvester creates new datasets for previously harvested periods

### ISSUE THREAD

**Issue by georgiana-b** [NextGeoss/ckanext-nextgeossharvest#195]
When running over a period that has has already been harvested, the EBAS harvester still creates new datasets. 

To reproduce, take for example this configuration:

```
{
"start_date": "2017-01-01T00:00:00Z",
"timeout": 100,
"make_private": false,
"update_all": true
}
```

Create a harvester, run it 2 times. It should only create new datasets. 
Create another harvester with the same configuration. Run it. Normally it should only update the datasets harvested by the initial harvester but you will notice it creates new datasets again.

Here is the output of the second harvester in my test.
![image](https://user-images.githubusercontent.com/8862002/74845393-3bcbc600-532f-11ea-8c50-29a15ed531ab.png)

This may be an issue with the results returned at the source or an issue with the harvester but it's worth investigating because it's not clear why are we missing those datasets in the first run.

**Comment by davidcordeiro-deimos** [comment]
@georgiana-b This "issue" is due to the pagination mechanism used by the data provider, furthermore the query does not allow any kind of sorting.

To give you an overview of the pagination mechanism, when you make query to the data provider, it returns 10 out of 100 available products plus a "resumptionToken" that allows you to go to the next "page" in the next query (which would return the results from 11-20).

This pagination mechanism together with **no sorting** mechanism makes that the same initial query might not return the same result. Thus, the behavior that you are observing.

I would like to also mention, that if you start in a query and "follow" the resumptionToken until the last page, you should not find any repeated datasets.

I know that this harvester behavior is not ideal, but these are the limitations from the data provider. 

If you have any other question please let me know.

**Comment by georgiana-b** [comment]
I see. Well, if you are aware of this behaviour and if you are sure it doesn't cause us to miss any datasets feel free to close the issue.

**Comment by davidcordeiro-deimos** [comment]
ACK
